CREATE DATABASE TUTORIAL;
USE TUTORIAL;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tb_stu;
CREATE TABLE tb_stu
(
	id int PRIMARY KEY AUTO_INCREMENT,
    name varchar(10) DEFAULT NULL,
    sex char(1) DEFAULT NULL,
    birthday date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO tb_stu VALUES (1,"张三",'男',"1998-02-06");
INSERT INTO tb_stu VALUES (2,"李四",'女',"1995-06-28");
INSERT INTO tb_stu VALUES (3,"王五",'女',"1999-11-23");
INSERT INTO tb_stu VALUES (4,"赵六",'男',"2000-05-30");